### ISSUE TITLE
FeatureRequest - Add Guild Name and rename Ignore Button

### ISSUE THREAD

**Issue by isitLoVe** [fs86/LFG_MatchMaker_TBC#3]
- Add the player guild name when clicking on the who button in the popup frame
- Rename the Ignore button to something like close. I thought you will chat ignore that player (not what I wanted).

**Comment by fs86** [comment]
The term "Close" does not describe what the button actually does. In fact, it ignores the respective LFG/LFM request so that it does not pop up a second time.

Can you describe in more detail what advantage it would have if the guild name is displayed in the popup window? When you click on the who button, a /who command is issued in the game. So you see the guild name in the chat.

**Comment by isitLoVe** [comment]
Regarding the Ignore button: then it would be the best to name it ignore reuquest to not confuse with ignore player.

/who outputs to the default chat frame, when I have another frame open (LFG), I dont see the /who output.

**Comment by fs86** [comment]
In version 1.0.3 the button text is now "Ignore requests". For the next version I will try to display the guild name in the popup window.

**Comment by fs86** [comment]
I will try to add the guild name for one of the next versions.

**Comment by fs86** [comment]
Implemented in 1.10.0
